### ISSUE TITLE
Questions Only - What device are we connecting this to??

### ISSUE THREAD

**Issue by austwhite** [rrooggiieerr/homeassistant-axaremote#1]
What are we actually wiring this up to?
The instructions are very vague.
What device is TX/RX connected to?  
Does it need an ESP device?  Does this need to be programmed?

**Comment by rrooggiieerr** [comment]
Hi! Thanks for asking. There are different ways you can wire this up. An ESP with [ESP-Link](https://github.com/jeelabs/esp-link) firmware is one option, using a serial to USB converter and some electronics is an other.

**Comment by austwhite** [comment]
With a USB to serial converter, you'd connect it directly to the Home Assistant device?

**Comment by rrooggiieerr** [comment]
That is indeed possible, the integration let's you select the serial port you've connected your AXA Remote to

**Comment by austwhite** [comment]
Thanks :)

**Comment by rrooggiieerr** [comment]
I actually have to update the GitHub repository with my code for serial over network bridges (ESP-Link), will look into that in the upcoming days. That's how I use my AXA Remotes and this integration mainly

**Comment by austwhite** [comment]
I'll watch this for when you update.   I have just got my first AXA Remote 2.0 and wanted to get it in Home Assistant.  Other projects use the LIN bus, but the parts are sometimes hard to find

**Comment by rrooggiieerr** [comment]
The LIN bus is basically only used as a level converter between 8 Volts, or whatever the AXA Remote is using and the TTL serial level. Other converters are maybe possible, but I just used the LIN bus as documented because I didn't bother. But if you're electronics skills are better than mine I'm eager to know how to do the level converting differently.

**Comment by austwhite** [comment]
I ended up making up a circuit based on the MCP2003A LIN transceiver chip that does all the conversion from the LIN bus to Serial, and can act as a LIN Master.    I managed to find a seller of the MCP2003A at a reasonable price.   There is also a MCP2003B if you prefer surface mount.   I am in Australia, so we don't always have access to components the same way as other countries do.  The MCP2003 is a LIN Tranceiver, it takes TX/RX TTL Serial and converts it to LIN Bus single wire.  It can be a LIN Master.   The circuit I used is not my design.  I found it on galagaking's Github page.  It uses MCP2003 as a LIN transceiver and connects to a WEMOS D1 Mini ESP device.   I just didn't wire BME/P280 into it. 
I also found out in the AXA Remote 2.0 the batteries are directly connected to the RJ12, positive to 1,6 and negative to 2,5 with the LIN Bus on 3,4.    Have to take that into account whenever any external voltage is applied to the RJ12 connector on the AXA 2.0.    

I kind of figured if I was going to have a wire connected to the Axa remote 2.0, might as well have it provide power as well.   I can likely utilise ESP-Link and your integration

**Comment by rrooggiieerr** [comment]
I've been in touch with galagaking too about the implementation. There is some room for improvement on my documentation, but I'm also using an external power supply.

So is my AXA Remote integration working for you now?

**Comment by austwhite** [comment]
Hi,
Your integration does work well.   I had found a fork of galagaking's work that seems to have more in it, but it looks like it has been changed so it won't run on a D1 Mini, but needs an ESP32.    Can't find it now of course......   

You can close this off if you like.   All questions have been answered now

Edit: found the fork: https://github.com/ellepdesk/espaxa

**Comment by rrooggiieerr** [comment]
That's great! Let me know which features you're missing.

Open percentage is still flaky, I need to look more into that when I've got time

**Comment by austwhite** [comment]
I don't think the Axa 2.0 remote can do open percentage.  It's more a guess at how far to open based on run time..... 

Thanks for all your help and support

**Comment by rrooggiieerr** [comment]
Yes it is a guess, but an educated guess can work quite well
